version: '3.3'
services:
  mysql_db_sadhustay:
    image: mysql:8.0
    container_name: mysql_db_sadhustay
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sadhu123
      MYSQL_DATABASE: sadhu_db
      MYSQL_USER: iamsadhu
      MYSQL_PASSWORD: sadhustay123
    ports:
      - "3309:3306"
    volumes:
      - /data/volumes/project/sadhustay/mysql:/var/lib/mysql
  phpmyadmin_sadhustay:
    container_name: phpmyadmin_container_sadhustay
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: on-failure
    environment:
      PMA_HOST: mysql_db_sadhustay
      # PMA_USER: root
      # PMA_PASSWORD: secret
    ports:
      - "0.0.0.0:8089:80"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1   

